### ISSUE TITLE
Issues  in function _radial_basis_functions.py

### ISSUE THREAD

**Issue by hongkunz** [dynamicslab/pykoopman#15]
This is the error message I got:

"pykoopman/observables/_radial_basis_functions.py:259
    match self.rbf_type:
          ^
SyntaxError: invalid syntax"

Please help. Thanks

**Comment by pswpswpsw** [comment]
@hongkunz You need to install python = ">=3.10". It is stated in setup.py. Matching is a new feature only after 3.10.

**Comment by hongkunz** [comment]
Thanks! Thank worked!
