### ISSUE TITLE
Example not working after installation

### ISSUE THREAD

**Issue by jehanzebchaudhry** [dynamicslab/pykoopman#16]
I installed the package using pip, and am trying to run the tutorial_koopman_edmdc example. However, I get error when trying to import as shown below:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-64b39faaac86> in <module>
      1 get_ipython().run_line_magic('matplotlib', 'inline')
      2 import pykoopman as pk
----> 3 from pykoopman.common.examples import vdp_osc, rk4, square_wave  # required for example system
      4 import matplotlib.pyplot as plt
      5 import numpy as np

ImportError: cannot import name 'vdp_osc' from 'pykoopman.common.examples' (/Users/jehanzeb/anaconda3/lib/python3.8/site-packages/pykoopman/common/examples.py)

**Comment by pswpswpsw** [comment]
@jehanzebchaudhry please try to install via the GitHub one. The one on Pypi is not updated yet.
