### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by jhtu** [dynamicslab/pykoopman#29]
I believe that in the [HAVOK/Lorenz example](https://pykoopman.readthedocs.io/en/master/tutorial_koopman_havok_3d_lorenz.html), in cell 9 under "Prediction using the HAVOK model", we should be plotting `xpred[:,j]`, not `xpred[:,i]`.  This (very minor) bug doesn't actually show up because it so happens that since `INDEX` is [0], [1], [2], or [1,2], we always have `i == j`.  However, if we were to choose `INDEX = [0, 2]`, then the bug would appear.

**Comment by pswpswpsw** [comment]
Thanks. Just fixed this bug.
