### ISSUE TITLE
No module named optht

### ISSUE THREAD

**Issue by xqb-python** [dynamicslab/pykoopman#30]
After installing pykoopman, I ran the corresponding program (import pykoopman as pk in Python 3.10.9) and found the following problem:
**ModuleNotFoundError: No module named 'optht'**

**Comment by xqb-python** [comment]
I downloaded the corresponding library according to the requirements. txt in the code, and then downloaded the "lighting "library, and there was no further error.

**Comment by pswpswpsw** [comment]
Yes. Please follow the instructions by installing the packages in the `requirements.txt`
