### ISSUE TITLE
AttributeError: 'Koopman' object has no attribute 'V'

### ISSUE THREAD

**Issue by xqb-python** [dynamicslab/pykoopman#31]
In the tutorial “Dynamic mode decomposition with control (DMDc) for a 128D system”，when i run the ：
DMDc = pk.regression.DMDc(svd_rank=11, svd_output_rank=10)
model = pk.Koopman(regressor=DMDc)
model.fit(torus.X.T, u=U[:,np.newaxis], dt=dt)
Phi_dmdc = model.V
torus.viz_all_modes(np.real(Phi_dmdc[:,::2]))
The program will report an error, displaying the error of “AttributeError: 'Koopman' object has no attribute 'V'”.

**Comment by pswpswpsw** [comment]
You are right. Instead of `model.V`, it should be `model.W` for the Koopman eigenmodes.

**Comment by pswpswpsw** [comment]
Check out the latest version of the package on github. It has been fixed.
