### ISSUE TITLE
Question about the difference between the function named '_compute_phi' and '_compute_psi'

### ISSUE THREAD

**Issue by AlbertJNU** [dynamicslab/pykoopman#32]
Take the _edmd.py in pykoopman.regression as an example. In this file, phi is computed as  self._ur.conj().T @ x_col, while psi is computed as self._tmp_compute_psi @ x_col. I can't figure out the true meaning behind the phi and psi, not to mention their difference. Could you please explain it in more detail by Mathematical formula? It would be more appreciated if there are corresponding articles to provide.

**Comment by pswpswpsw** [comment]
Take a look at the figure 1 in the paper https://arxiv.org/pdf/2306.12962.pdf You will see psi and phi are different. psi is for Koopman eigenfunctions, and phi are just for observables.

**Comment by AlbertJNU** [comment]
Thank you for your reply. I have understood!
