### ISSUE TITLE
Fitting 

### ISSUE THREAD

**Issue by batouldaou** [dynamicslab/pykoopman#33]
Hello,
I am trying to rerun the tutorial code or get the observables names using the polynomial class but every time I get an error. When trying to obtain the get_features_names it isnt defined in the Base file and for the observable the model.koopman(obs=pk.observable.Polynomial(degree =2) regression= EDMDc())  always gives the error that model is not fitted. The tutorial I am trying to follow is the eigen functions with slow manifold and even running it on my pc doesn't work. Could anyone help me out?

**Comment by jaewook570** [comment]
It's a problem with the scikit-learn version. Try installing an earlier version.
For example, to install the version 1.0.2 using pip, run this from cmd:

pip install scikit-learn==1.0.2

**Comment by pswpswpsw** [comment]
Thanks for pointing this out. `scikit-learn` keeps changing their once in a while. I am using `1.1.3` which is fine. I will add that to the requirement.
