### ISSUE TITLE
PyKoopman for coupled PDEs

### ISSUE THREAD

**Issue by lsptrsn** [dynamicslab/pykoopman#34]
I would like to apply PyKoopman to a coupled PDE, let's say:

$\frac{\partial X}{\partial t} = \frac{\partial X}{\partial z} + T$ \
$\frac{\partial T}{\partial t} = X - \frac{\partial T}{\partial z}$

After discretizing for z and solving this system with some initial values I have the matrices t, z, X, T.
t.shape = (150,)
z.shape = (151,)
X.shape = (150, 151)
T.shape= (150, 151)

In which form can I input X and T into _model.fit(x, dt=dt)_? Does pyKoopman currently support this?

**Comment by pswpswpsw** [comment]
You want to try DMD first on this problem. And it will work amazingly well. So the short answer is yes.
