### ISSUE TITLE
`python setup.py install` doesn't work 

### ISSUE THREAD

**Issue by ulf1** [dynamicslab/pykoopman#38]
https://github.com/dynamicslab/pykoopman/blob/a3c6f98219a21af9ef73d34a6cbac33594d2984a/README.rst?plain=1#L173

the file `setup.py` doesn't exist

**Comment by pswpswpsw** [comment]
yes. I just corrected and removed the setuptools. you can just use `python -m pip install -e .` to use the user version and `python -m pip install -e .[dev]` for the developer version.
