### ISSUE TITLE
no version ranges for dependencies

### ISSUE THREAD

**Issue by ulf1** [dynamicslab/pykoopman#39]
https://github.com/dynamicslab/pykoopman/blob/a3c6f98219a21af9ef73d34a6cbac33594d2984a/requirements.txt#L2

**Comment by ulf1** [comment]
for example `numpy>=1,<2` instead of just `numpy`

Why? breaking changes can happen. a maintainer should ensure that any version of the maintained package works (e.g. when installing an old version `pykoopman` in 5 years to reproduce a study, or simply deploy an old docker container)

**Comment by ulf1** [comment]
note tthat version range applies to `setup.py` as well

**Comment by Dionysus7777777** [comment]
the version of python is adivced to be 3.10 and you ‘d better do not use pip to down the pykoopman，i suggest that you download it from github

**Comment by pswpswpsw** [comment]
you are very correct about this.. In fact I observed some of those issues and complained about it.. I have corrected it
