### ISSUE TITLE
changing the activation function 

### ISSUE THREAD

**Issue by Dionysus7777777** [dynamicslab/pykoopman#42]
When using NNDMD, it seems that changing the activation function results in an error. Could this be because the library does not define activation functions other than linear?

**Comment by pswpswpsw** [comment]
So basically for decoder, you must use linear. Because otherwise the concept of Koopman modes is gone. Since this package is designed only for Koopman operator, not Koopman-inspired etc, we decided to discourage the use of nonlinear decoder.

**Comment by Dionysus7777777** [comment]
So in Koopman theory, do all activation functions of neural networks have to be linear? In my previous understanding, only the Koopman operator layer needs to be linear; the activation functions of the encoder and decoder do not necessarily need to be linear.

**Comment by Dionysus7777777** [comment]
and thanks for your reply and happy Chinese new year！

**Comment by pswpswpsw** [comment]
> So in Koopman theory, do all activation functions of neural networks have to be linear? In my previous understanding, only the Koopman operator layer needs to be linear; the activation functions of the encoder and decoder do not necessarily need to be linear.

Koopman theory has nothing to do with neural network. But the entire idea of Koopman modes are only for the observables that can be spanned (i.e., linear weighted sum) by eigenfunctions. So you need the decoder in the neural network to be linear in order to not break the idea of Koopman modes.

**Comment by Dionysus7777777** [comment]
[Deep learning for universal linear embeddings of nonlinear dynamics.pdf](https://github.com/dynamicslab/pykoopman/files/14237366/Deep.learning.for.universal.linear.embeddings.of.nonlinear.dynamics.pdf)

**Comment by pswpswpsw** [comment]
Linear embedding is not the same as learning an invariant subspace that spans the state. I also had a published paper using nonlinear decoder, but I always say that's linear embedding, not to confuse with the classical approximation of Koopman operator.

**Comment by Dionysus7777777** [comment]
thanks a lot

**Comment by Dionysus7777777** [comment]
thanks
