### ISSUE TITLE
NAN issues

### ISSUE THREAD

**Issue by Dionysus7777777** [dynamicslab/pykoopman#45]
I encounter NaN (Not a Number) issues when training certain specific functions through the network. There are no NaN values in my training set, so I suspect it's due to gradient explosion. I'm unsure how to resolve this problem
<img width="477" alt="image" src="https://github.com/dynamicslab/pykoopman/assets/144111054/0f736dc3-8429-478e-91a4-2c546cf4a8dd">

**Comment by JDRanpariya** [comment]
How did you get around it? I'm facing similar issue.
