### ISSUE TITLE
Array shape issues with non-identity observables

### ISSUE THREAD

**Issue by bsosis** [dynamicslab/pykoopman#6]
Currently non-identity observables have problems handling one-dimensional input vectors. `validate_input` reshapes them into `(n,1)` arrays, but this isn't always the desired behavior: sometimes the array elements are different features rather than different samples, in which case the array should have shape `(1,n)`. Usually you can fix this by just reshaping your array to be `(1,n)` to begin with -- except when running running `simulate` in `koopman.py`. Even if the `x0` you input has shape `(1,n)`, the _first_ call to `predict` will work as expected, but subsequent iterations will take one-dimensional slices of the array `y`, which are then reshaped to `(n,1)` arrays by `validate_input` leading to errors.

My current "fix" is to simply replace the line `y[k + 1] = self.predict(y[k])` in `simulate` with `y[k + 1] = self.predict(y[k].reshape(1, -1))`. This passes the unit tests and seems to allow `predict` to work for non-identity observables, but I don't understand this code nearly well enough to say whether this is the right way to fix this or if this will cause other issues. (I think a similar fix works for when `u` is not `None`: `y[k + 1] = self.predict(y[k].reshape(1,-1), u[k + 1].reshape(1,-1))`, but I'm even less confident here.) It might also be better to do the reshaping in some other part of the code rather than here. Different parts of the code seem to depend on various things being specific shapes in ways that I don't understand, so it's entirely possible that this will cause problems elsewhere.

I hope this helps!

**Comment by briandesilva** [comment]
Thanks for pointing this out to us. Your detailed explanation was especially helpful. I've implemented the fix you recommended and created a new release (v0.2.0) with the changes. You should be able to get them with a
```bash
python -m pip install --upgrade pykoopman
```
